server:
  host: localhost
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: Xxagrorog123
  dbname: shipment_api

filter:
  enabled: true
  expected_num_elements: 10000000
  false_positive_probability: 0.1
